import type {
  KYRProfile,
  CommunityEvent,
  CheckIn,
  BoardPost,
  Celebration,
  Visitor,
  Mentor,
  DiscussionThread,
  Announcement,
} from '@/types'

export const mockResidents: KYRProfile[] = [
  {
    id: 'res-1',
    userId: 'user-1',
    fullName: 'Alex Chen',
    preferredName: 'Alex',
    pronouns: 'they/them',
    role: 'Founder',
    company: 'NeuralPath AI',
    workingOn: 'AI-powered legal document analysis',
    expertise: ['Machine Learning', 'Python', 'Product Strategy'],
    seeking: ['Frontend Engineer', 'Legal Advisor', 'Seed Funding'],
    workStyle: 'early-bird',
    collaborationPreference: 'pair',
    noisePreference: 'ambient',
    meetingPreference: 'morning',
    hometown: 'San Francisco, CA',
    languages: ['English', 'Mandarin'],
    hobbies: ['Rock Climbing', 'Board Games', 'Photography'],
    dietaryRestrictions: ['Vegetarian'],
    favoriteCuisine: ['Japanese', 'Mexican'],
    coffeeOrder: 'Oat milk latte',
    superpower: 'Can debug any code at 2am',
    currentlyReading: 'The Lean Startup',
    walkSong: 'Eye of the Tiger',
    slackHandle: '@alex.chen',
    linkedIn: 'linkedin.com/in/alexchen',
    avatarUrl: undefined,
    bio: 'Building the future of legal tech. Previously at Google.',
    isPublic: true,
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'res-2',
    userId: 'user-2',
    fullName: 'Sarah Johnson',
    preferredName: 'Sarah',
    pronouns: 'she/her',
    role: 'CTO',
    company: 'GreenMetrics',
    workingOn: 'Sustainability tracking platform for enterprises',
    expertise: ['React', 'Node.js', 'AWS', 'Climate Tech'],
    seeking: ['Climate Data Partners', 'Series A Investors'],
    workStyle: 'flexible',
    collaborationPreference: 'team',
    noisePreference: 'any',
    meetingPreference: 'afternoon',
    hometown: 'Austin, TX',
    languages: ['English', 'Spanish'],
    hobbies: ['Hiking', 'Cooking', 'Yoga'],
    dietaryRestrictions: [],
    favoriteCuisine: ['Thai', 'Italian'],
    coffeeOrder: 'Cold brew, black',
    superpower: 'Remembers everyone\'s name',
    currentlyWatching: 'Severance',
    slackHandle: '@sarah.j',
    avatarUrl: undefined,
    bio: 'Making sustainability measurable. 10+ years in enterprise software.',
    isPublic: true,
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-02-15T00:00:00Z',
  },
  {
    id: 'res-3',
    userId: 'user-3',
    fullName: 'Marcus Williams',
    preferredName: 'Marc',
    pronouns: 'he/him',
    role: 'Founder',
    company: 'FinFlow',
    workingOn: 'Automated bookkeeping for freelancers',
    expertise: ['Finance', 'UX Design', 'Flutter'],
    seeking: ['Mobile Developer', 'Accountant Advisors'],
    workStyle: 'night-owl',
    collaborationPreference: 'solo',
    noisePreference: 'silent',
    meetingPreference: 'evening',
    hometown: 'Chicago, IL',
    languages: ['English'],
    hobbies: ['Jazz Piano', 'Chess', 'Running'],
    dietaryRestrictions: ['Gluten-free'],
    favoriteCuisine: ['Korean', 'Indian'],
    coffeeOrder: 'Espresso',
    superpower: 'Can explain any financial concept simply',
    currentlyReading: 'Zero to One',
    slackHandle: '@marc.w',
    linkedIn: 'linkedin.com/in/marcuswilliams',
    avatarUrl: undefined,
    bio: 'Former Goldman Sachs. Democratizing financial tools.',
    isPublic: true,
    createdAt: '2024-01-20T00:00:00Z',
    updatedAt: '2024-02-10T00:00:00Z',
  },
  {
    id: 'res-4',
    userId: 'user-4',
    fullName: 'Priya Sharma',
    preferredName: 'Priya',
    pronouns: 'she/her',
    role: 'Designer',
    company: 'Freelance',
    workingOn: 'Building my design studio',
    expertise: ['Brand Design', 'Figma', 'Motion Design', 'Web3'],
    seeking: ['Startup Clients', 'Design Partners'],
    workStyle: 'flexible',
    collaborationPreference: 'any',
    noisePreference: 'music',
    meetingPreference: 'morning',
    hometown: 'Mumbai, India',
    languages: ['English', 'Hindi', 'Marathi'],
    hobbies: ['Illustration', 'Dance', 'Travel'],
    dietaryRestrictions: ['Vegetarian', 'No eggs'],
    favoriteCuisine: ['Indian', 'Mediterranean'],
    coffeeOrder: 'Chai latte',
    superpower: 'Turns complex ideas into simple visuals',
    currentlyWatching: 'Abstract: The Art of Design',
    slackHandle: '@priya.design',
    personalSite: 'priyasharma.design',
    avatarUrl: undefined,
    bio: 'Award-winning designer. Making startups look good.',
    isPublic: true,
    createdAt: '2024-02-05T00:00:00Z',
    updatedAt: '2024-02-20T00:00:00Z',
  },
  {
    id: 'res-5',
    userId: 'user-5',
    fullName: 'James O\'Connor',
    preferredName: 'JC',
    pronouns: 'he/him',
    role: 'Engineer',
    company: 'DataSync',
    workingOn: 'Real-time data sync infrastructure',
    expertise: ['Rust', 'Distributed Systems', 'PostgreSQL'],
    seeking: ['Co-founder', 'Angel Investment'],
    workStyle: 'early-bird',
    collaborationPreference: 'pair',
    noisePreference: 'ambient',
    meetingPreference: 'any',
    hometown: 'Dublin, Ireland',
    languages: ['English', 'Irish'],
    hobbies: ['Rugby', 'Whiskey Tasting', 'Woodworking'],
    dietaryRestrictions: [],
    favoriteCuisine: ['Irish', 'BBQ'],
    coffeeOrder: 'Americano',
    superpower: 'Optimizes everything, including breakfast routine',
    currentlyReading: 'Designing Data-Intensive Applications',
    slackHandle: '@jc.oconnor',
    avatarUrl: undefined,
    bio: 'Ex-Stripe infrastructure. Building better databases.',
    isPublic: true,
    createdAt: '2024-01-25T00:00:00Z',
    updatedAt: '2024-02-18T00:00:00Z',
  },
]

export const mockEvents: CommunityEvent[] = [
  {
    id: 'evt-1',
    title: 'Founder Lunch & Learn: Fundraising 101',
    description: 'Join us for a casual lunch where we\'ll discuss the basics of fundraising, from pitch decks to term sheets. Bring your questions!',
    category: 'learning',
    date: new Date().toISOString().split('T')[0],
    startTime: '12:00',
    endTime: '13:30',
    isAllDay: false,
    isRecurring: true,
    recurrencePattern: 'Every Thursday',
    location: 'Collab Zone',
    isVirtual: false,
    capacity: 20,
    spotsRemaining: 8,
    hasWaitlist: true,
    hostId: 'mentor-1',
    hostName: 'David Park',
    rsvpCount: 12,
    comments: [],
    tags: ['fundraising', 'lunch', 'learning'],
    isHighlight: true,
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'evt-2',
    title: 'Rooftop Social: Friday Sunset',
    description: 'End the week right! Join fellow founders and the Sanctuary team for drinks and conversation on the rooftop. Bring a friend!',
    category: 'social',
    date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    startTime: '17:00',
    endTime: '20:00',
    isAllDay: false,
    isRecurring: true,
    recurrencePattern: 'Every Friday',
    location: 'Rooftop',
    isVirtual: false,
    capacity: 50,
    spotsRemaining: 35,
    hasWaitlist: false,
    hostId: 'staff-1',
    hostName: 'Sanctuary Team',
    rsvpCount: 15,
    comments: [],
    tags: ['social', 'networking', 'drinks'],
    isHighlight: true,
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'evt-3',
    title: 'Morning Meditation',
    description: 'Start your day with 20 minutes of guided meditation. All levels welcome. Mats provided.',
    category: 'wellness',
    date: new Date().toISOString().split('T')[0],
    startTime: '08:00',
    endTime: '08:30',
    isAllDay: false,
    isRecurring: true,
    recurrencePattern: 'Mon, Wed, Fri',
    location: 'Quiet Zone',
    isVirtual: false,
    capacity: 10,
    spotsRemaining: 6,
    hasWaitlist: false,
    hostId: 'res-4',
    hostName: 'Priya Sharma',
    rsvpCount: 4,
    comments: [],
    tags: ['wellness', 'meditation', 'morning'],
    isHighlight: false,
    createdAt: '2024-02-10T00:00:00Z',
  },
  {
    id: 'evt-4',
    title: 'Demo Day: February Cohort',
    description: 'Watch 5 startups from our February cohort present their progress. Investors and mentors welcome.',
    category: 'pitch',
    date: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
    startTime: '14:00',
    endTime: '17:00',
    isAllDay: false,
    isRecurring: false,
    location: 'Main Event Space',
    isVirtual: true,
    virtualLink: 'https://zoom.us/j/example',
    capacity: 100,
    spotsRemaining: 45,
    hasWaitlist: true,
    hostId: 'staff-1',
    hostName: 'Sanctuary Team',
    rsvpCount: 55,
    comments: [],
    tags: ['demo', 'pitch', 'investors'],
    isHighlight: true,
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'evt-5',
    title: 'Design Systems Workshop',
    description: 'Learn how to build scalable design systems for your startup. Priya will share her framework and tools.',
    category: 'workshop',
    date: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
    startTime: '15:00',
    endTime: '17:00',
    isAllDay: false,
    isRecurring: false,
    location: 'Meeting Room A',
    isVirtual: false,
    capacity: 15,
    spotsRemaining: 3,
    hasWaitlist: true,
    hostId: 'res-4',
    hostName: 'Priya Sharma',
    rsvpCount: 12,
    comments: [],
    tags: ['design', 'workshop', 'figma'],
    isHighlight: false,
    createdAt: '2024-02-15T00:00:00Z',
  },
]

export const mockCheckIns: CheckIn[] = [
  {
    id: 'ci-1',
    userId: 'user-2',
    userName: 'Sarah Johnson',
    userRole: 'CTO',
    userCompany: 'GreenMetrics',
    checkInTime: new Date(Date.now() - 3600000 * 3).toISOString(),
    location: 'main-floor',
    status: 'Heads down on funding deck',
    isVisitor: false,
  },
  {
    id: 'ci-2',
    userId: 'user-3',
    userName: 'Marcus Williams',
    userRole: 'Founder',
    userCompany: 'FinFlow',
    checkInTime: new Date(Date.now() - 3600000 * 2).toISOString(),
    location: 'quiet-zone',
    status: 'Deep work mode - shipping v2',
    isVisitor: false,
  },
  {
    id: 'ci-3',
    userId: 'user-4',
    userName: 'Priya Sharma',
    userRole: 'Designer',
    checkInTime: new Date(Date.now() - 3600000).toISOString(),
    location: 'collab-zone',
    status: 'Open to chat about design!',
    isVisitor: false,
  },
  {
    id: 'ci-4',
    userId: 'user-5',
    userName: 'James O\'Connor',
    userRole: 'Engineer',
    userCompany: 'DataSync',
    checkInTime: new Date(Date.now() - 1800000).toISOString(),
    location: 'cafe',
    status: 'Coffee + code review',
    isVisitor: false,
  },
]

export const mockVisitors: Visitor[] = [
  {
    id: 'vis-1',
    name: 'Michael Torres',
    company: 'Sequoia Capital',
    purpose: 'Meeting with GreenMetrics',
    hostId: 'user-2',
    hostName: 'Sarah Johnson',
    checkInTime: new Date(Date.now() - 1800000).toISOString(),
    badgeNumber: 'V-042',
  },
  {
    id: 'vis-2',
    name: 'Emily Zhang',
    company: 'TechCrunch',
    purpose: 'Interview with founders',
    hostId: 'staff-1',
    hostName: 'Sanctuary Team',
    checkInTime: new Date(Date.now() - 3600000).toISOString(),
    badgeNumber: 'V-043',
  },
]

export const mockPosts: BoardPost[] = [
  {
    id: 'post-1',
    authorId: 'user-4',
    authorName: 'Priya Sharma',
    title: '🎨 Offering free logo feedback this week!',
    content: 'Working on a blog post about startup branding. Happy to give quick feedback on anyone\'s logo or brand identity. DM me on Slack!',
    category: 'offer',
    reactions: [
      { emoji: '🙏', count: 5, userIds: ['user-1', 'user-2', 'user-3', 'user-5', 'user-6'] },
      { emoji: '❤️', count: 3, userIds: ['user-1', 'user-2', 'user-7'] },
    ],
    commentCount: 4,
    isPinned: false,
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'post-2',
    authorId: 'staff-1',
    authorName: 'Sanctuary Team',
    title: '📢 Building maintenance: Sunday 6am-9am',
    content: 'Quick heads up - there will be scheduled maintenance this Sunday morning. Building will be accessible but elevators may be offline. Plan ahead if you\'re an early bird!',
    category: 'announcement',
    reactions: [
      { emoji: '👍', count: 8, userIds: ['user-1', 'user-2', 'user-3', 'user-4', 'user-5', 'user-6', 'user-7', 'user-8'] },
    ],
    commentCount: 2,
    isPinned: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'post-3',
    authorId: 'user-3',
    authorName: 'Marcus Williams',
    title: 'Looking for React Native dev recommendations',
    content: 'We\'re expanding the FinFlow mobile app and looking for contractor recommendations. Anyone worked with great RN devs recently?',
    category: 'ask',
    reactions: [
      { emoji: '🤔', count: 2, userIds: ['user-1', 'user-5'] },
    ],
    commentCount: 6,
    isPinned: false,
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'post-4',
    authorId: 'user-5',
    authorName: 'James O\'Connor',
    title: '🎉 Shoutout to Alex for the debugging help!',
    content: 'Spent 3 hours on a race condition yesterday. Alex walked by, looked at my screen for 30 seconds, and found it. True superpower!',
    category: 'shoutout',
    reactions: [
      { emoji: '🎉', count: 12, userIds: ['user-2', 'user-3', 'user-4', 'user-6', 'user-7', 'user-8', 'user-9', 'user-10', 'user-11', 'user-12', 'user-13', 'user-14'] },
      { emoji: '🧙', count: 4, userIds: ['user-2', 'user-3', 'user-4', 'user-5'] },
    ],
    commentCount: 3,
    isPinned: false,
    createdAt: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
]

export const mockCelebrations: Celebration[] = [
  {
    id: 'cel-1',
    userId: 'user-2',
    userName: 'Sarah Johnson',
    type: 'funding',
    title: 'GreenMetrics raised $2M seed!',
    description: 'Led by Sequoia Capital',
    date: new Date().toISOString().split('T')[0],
  },
  {
    id: 'cel-2',
    userId: 'user-5',
    userName: 'James O\'Connor',
    type: 'birthday',
    title: 'Happy Birthday JC!',
    date: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
  },
  {
    id: 'cel-3',
    userId: 'user-1',
    userName: 'Alex Chen',
    type: 'work-anniversary',
    title: '1 year at Sanctuary!',
    date: new Date(Date.now() + 4 * 86400000).toISOString().split('T')[0],
  },
]

export const mockMentors: Mentor[] = [
  {
    id: 'mentor-1',
    name: 'David Park',
    title: 'General Partner',
    company: 'Horizon Ventures',
    bio: 'Former CTO of a $2B SaaS company. 15 years in enterprise software, now helping founders build scalable businesses. Specializes in B2B go-to-market and technical architecture.',
    expertise: ['fundraising', 'product', 'engineering'],
    tags: ['SaaS', 'B2B', 'Enterprise', 'Series A'],
    availability: 'available',
    officeHours: 'Thursdays 2:00 - 5:00 PM',
    linkedIn: 'linkedin.com/in/davidpark',
    menteeCount: 8,
    rating: 4.9,
    sessionCount: 124,
    createdAt: '2023-06-01T00:00:00Z',
  },
  {
    id: 'mentor-2',
    name: 'Sarah Kim',
    title: 'VP of Growth',
    company: 'Ex-Stripe',
    bio: 'Scaled Stripe\'s SMB segment from $0 to $500M ARR. Expert in product-led growth, pricing strategy, and go-to-market. Passionate about helping early-stage founders find product-market fit.',
    expertise: ['marketing', 'sales', 'product'],
    tags: ['Growth', 'PLG', 'Pricing', 'PMF'],
    availability: 'available',
    officeHours: 'Tuesdays 10:00 AM - 1:00 PM',
    linkedIn: 'linkedin.com/in/sarahkim',
    twitter: '@sarahkim_growth',
    menteeCount: 12,
    rating: 4.8,
    sessionCount: 89,
    createdAt: '2023-08-15T00:00:00Z',
  },
  {
    id: 'mentor-3',
    name: 'Roberto Alvarez',
    title: 'Founding Partner',
    company: 'Alvarez Law Group',
    bio: 'Startup attorney with 20+ years of experience. Helped 200+ companies with incorporation, fundraising docs, IP strategy, and M&A. SAFE notes expert.',
    expertise: ['legal', 'fundraising'],
    tags: ['Corporate Law', 'IP', 'SAFE Notes', 'Term Sheets'],
    availability: 'limited',
    nextAvailable: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
    officeHours: 'By appointment',
    linkedIn: 'linkedin.com/in/robertoalvarez',
    menteeCount: 15,
    rating: 4.9,
    sessionCount: 210,
    createdAt: '2023-01-10T00:00:00Z',
  },
  {
    id: 'mentor-4',
    name: 'Linda Okafor',
    title: 'Design Director',
    company: 'Ex-Figma',
    bio: 'Led design for Figma\'s collaboration features. 12 years in product design across consumer and enterprise. Focuses on design systems, user research, and team building.',
    expertise: ['design', 'product'],
    tags: ['Product Design', 'Design Systems', 'User Research', 'Figma'],
    availability: 'available',
    officeHours: 'Wednesdays 3:00 - 5:00 PM',
    linkedIn: 'linkedin.com/in/lindaokafor',
    personalSite: 'lindaokafor.design',
    menteeCount: 6,
    rating: 5.0,
    sessionCount: 67,
    createdAt: '2023-09-20T00:00:00Z',
  },
  {
    id: 'mentor-5',
    name: 'Raj Patel',
    title: 'CFO',
    company: 'Ex-Coinbase',
    bio: 'Former CFO at Coinbase through IPO. Deep expertise in financial modeling, fundraising strategy, and corporate finance. Helps founders build investor-ready financial plans.',
    expertise: ['finance', 'fundraising', 'operations'],
    tags: ['Financial Modeling', 'IPO', 'FinTech', 'Unit Economics'],
    availability: 'available',
    officeHours: 'Mondays 1:00 - 4:00 PM',
    linkedIn: 'linkedin.com/in/rajpatel',
    menteeCount: 10,
    rating: 4.7,
    sessionCount: 156,
    createdAt: '2023-04-05T00:00:00Z',
  },
  {
    id: 'mentor-6',
    name: 'Aisha Mohamed',
    title: 'Head of Talent',
    company: 'Benchmark Capital',
    bio: 'Built talent functions at 3 unicorns. Expert in startup hiring, culture building, and compensation design. Helps founders make their first 10 hires.',
    expertise: ['hr', 'operations'],
    tags: ['Hiring', 'Culture', 'Compensation', 'Team Building'],
    availability: 'unavailable',
    nextAvailable: new Date(Date.now() + 14 * 86400000).toISOString().split('T')[0],
    menteeCount: 9,
    rating: 4.8,
    sessionCount: 98,
    createdAt: '2023-07-12T00:00:00Z',
  },
]

export const mockDiscussions: DiscussionThread[] = [
  {
    id: 'disc-1',
    authorId: 'user-2',
    authorName: 'Sarah Johnson',
    authorRole: 'CTO, GreenMetrics',
    title: 'Best practices for SOC 2 compliance as an early-stage startup?',
    content: 'We just got our first enterprise customer and they are asking about SOC 2. We are a 5-person team and not sure where to start. Has anyone gone through this process recently? What tools did you use? How long did it take? Any recommendations for compliance platforms vs. doing it manually?',
    tags: ['technical', 'legal', 'advice'],
    replies: [
      {
        id: 'reply-1-1',
        threadId: 'disc-1',
        authorId: 'user-5',
        authorName: 'James O\'Connor',
        authorRole: 'Engineer, DataSync',
        content: 'We went through this last year. Used Vanta and it made everything much smoother. Took about 3 months from start to audit. Happy to walk you through our setup. The biggest time sink was writing policies, but Vanta has good templates.',
        upvotes: 8,
        isAcceptedAnswer: true,
        createdAt: new Date(Date.now() - 3600000 * 20).toISOString(),
      },
      {
        id: 'reply-1-2',
        threadId: 'disc-1',
        authorId: 'mentor-3',
        authorName: 'Roberto Alvarez',
        authorRole: 'Mentor, Legal',
        content: 'Great question. I would also recommend starting with SOC 2 Type I before Type II. Type I is a point-in-time assessment which is faster and cheaper. Most enterprise customers will accept Type I while you work toward Type II. Let\'s chat during my office hours this week.',
        upvotes: 12,
        isAcceptedAnswer: false,
        createdAt: new Date(Date.now() - 3600000 * 18).toISOString(),
      },
      {
        id: 'reply-1-3',
        threadId: 'disc-1',
        authorId: 'user-1',
        authorName: 'Alex Chen',
        authorRole: 'Founder, NeuralPath AI',
        content: 'Second Vanta. Also check out Drata - they have a startup program with significant discounts. We are going through the process right now.',
        upvotes: 5,
        isAcceptedAnswer: false,
        createdAt: new Date(Date.now() - 3600000 * 15).toISOString(),
      },
    ],
    replyCount: 3,
    viewCount: 47,
    upvotes: 15,
    isPinned: false,
    isResolved: true,
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    lastActivityAt: new Date(Date.now() - 3600000 * 15).toISOString(),
  },
  {
    id: 'disc-2',
    authorId: 'user-3',
    authorName: 'Marcus Williams',
    authorRole: 'Founder, FinFlow',
    title: 'How are you handling pricing for your MVP?',
    content: 'We are about to launch our MVP and struggling with pricing. Our product is an automated bookkeeping tool for freelancers. We are considering freemium vs. free trial vs. usage-based pricing. What has worked for others? Especially interested in hearing from fellow fintech founders.',
    tags: ['product', 'marketing', 'advice'],
    replies: [
      {
        id: 'reply-2-1',
        threadId: 'disc-2',
        authorId: 'mentor-2',
        authorName: 'Sarah Kim',
        authorRole: 'Mentor, Growth',
        content: 'For fintech targeting freelancers, I would strongly recommend starting with a free tier + paid tier model. Freelancers are price-sensitive but once they see value, they convert well. At Stripe, we found that usage-based pricing for SMBs created too much anxiety. Fixed tiers with clear value props work better. Come to my office hours this Tuesday and we can map out your pricing page together.',
        upvotes: 18,
        isAcceptedAnswer: false,
        createdAt: new Date(Date.now() - 3600000 * 10).toISOString(),
      },
      {
        id: 'reply-2-2',
        threadId: 'disc-2',
        authorId: 'user-4',
        authorName: 'Priya Sharma',
        authorRole: 'Designer',
        content: 'From a UX perspective, make sure your pricing page clearly shows what they get at each tier. I can help design the pricing page if you want - have done a few of these recently.',
        upvotes: 6,
        isAcceptedAnswer: false,
        createdAt: new Date(Date.now() - 3600000 * 8).toISOString(),
      },
    ],
    replyCount: 2,
    viewCount: 63,
    upvotes: 22,
    isPinned: false,
    isResolved: false,
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    lastActivityAt: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: 'disc-3',
    authorId: 'user-1',
    authorName: 'Alex Chen',
    authorRole: 'Founder, NeuralPath AI',
    title: 'Recommendations for AI/ML infrastructure providers?',
    content: 'We are hitting the limits of our current GPU setup and need to scale our inference pipeline. Looking at options like Replicate, Modal, Banana.dev, RunPod etc. Anyone have experience with these? Our workload is primarily transformer-based NLP models with variable traffic. Need good cold start times.',
    tags: ['technical', 'advice'],
    replies: [
      {
        id: 'reply-3-1',
        threadId: 'disc-3',
        authorId: 'user-5',
        authorName: 'James O\'Connor',
        authorRole: 'Engineer, DataSync',
        content: 'We evaluated several providers last quarter. Modal has been great for us - the developer experience is excellent and their cold start times are the best we tested. RunPod is cheaper for sustained workloads but the DX is not as polished. For variable traffic, Modal\'s autoscaling is hard to beat.',
        upvotes: 11,
        isAcceptedAnswer: false,
        createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
      },
    ],
    replyCount: 1,
    viewCount: 31,
    upvotes: 9,
    isPinned: false,
    isResolved: false,
    createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    lastActivityAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'disc-4',
    authorId: 'staff-1',
    authorName: 'Sanctuary Team',
    authorRole: 'Community',
    title: 'Welcome Thread: Introduce yourself!',
    content: 'Welcome to the Sanctuary community forum! This is the place to introduce yourself, share what you are building, and connect with fellow founders, mentors, and partners. Drop a comment below with your name, what you are working on, and one fun fact about yourself.',
    tags: ['general'],
    replies: [],
    replyCount: 24,
    viewCount: 312,
    upvotes: 45,
    isPinned: true,
    isResolved: false,
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    lastActivityAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'disc-5',
    authorId: 'user-4',
    authorName: 'Priya Sharma',
    authorRole: 'Designer',
    title: 'Anyone interested in a weekly design critique session?',
    content: 'I am thinking of starting a weekly design critique session where founders can bring their product designs for feedback. Would be informal - just sharing screens and giving constructive feedback. Thinking Thursday afternoons? Would anyone be interested?',
    tags: ['general', 'product'],
    replies: [
      {
        id: 'reply-5-1',
        threadId: 'disc-5',
        authorId: 'user-2',
        authorName: 'Sarah Johnson',
        authorRole: 'CTO, GreenMetrics',
        content: 'Yes! We desperately need design feedback. Would love to bring our dashboard redesign. Thursday afternoons work perfectly.',
        upvotes: 4,
        isAcceptedAnswer: false,
        createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
      },
      {
        id: 'reply-5-2',
        threadId: 'disc-5',
        authorId: 'user-3',
        authorName: 'Marcus Williams',
        authorRole: 'Founder, FinFlow',
        content: 'Count me in! Our onboarding flow could definitely use some expert eyes.',
        upvotes: 3,
        isAcceptedAnswer: false,
        createdAt: new Date(Date.now() - 3600000 * 44).toISOString(),
      },
    ],
    replyCount: 2,
    viewCount: 28,
    upvotes: 14,
    isPinned: false,
    isResolved: false,
    createdAt: new Date(Date.now() - 3600000 * 50).toISOString(),
    lastActivityAt: new Date(Date.now() - 3600000 * 44).toISOString(),
  },
]

export const mockAnnouncements: Announcement[] = [
  {
    id: 'ann-1',
    authorId: 'staff-1',
    authorName: 'Sanctuary Team',
    authorRole: 'Community',
    title: 'Demo Day: February Cohort - Next Thursday',
    content: 'Mark your calendars! Our February cohort will be presenting their progress at Demo Day next Thursday from 2-5 PM in the Main Event Space. We will have 5 startups presenting, followed by a networking reception. Investors and mentors are especially encouraged to attend. Virtual attendance is also available via Zoom. RSVP on the events page.',
    priority: 'important',
    tags: ['demo-day', 'cohort', 'investors'],
    isPinned: true,
    readBy: ['user-1', 'user-2', 'user-3'],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'ann-2',
    authorId: 'staff-1',
    authorName: 'Sanctuary Team',
    authorRole: 'Operations',
    title: 'New Mentor: Sarah Kim joins the Sanctuary network',
    content: 'We are thrilled to welcome Sarah Kim as our newest mentor! Sarah was VP of Growth at Stripe where she scaled the SMB segment from $0 to $500M ARR. She specializes in product-led growth, pricing strategy, and go-to-market. Her office hours will be Tuesdays from 10 AM to 1 PM. Book a slot on the mentors page.',
    priority: 'normal',
    tags: ['mentor', 'growth', 'welcome'],
    isPinned: false,
    readBy: ['user-1', 'user-2', 'user-4', 'user-5'],
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'ann-3',
    authorId: 'staff-1',
    authorName: 'Sanctuary Team',
    authorRole: 'Operations',
    title: 'Building Maintenance: Sunday 6 AM - 9 AM',
    content: 'Scheduled maintenance this Sunday morning from 6 AM to 9 AM. The building will be accessible but elevators may be temporarily offline. Please plan accordingly if you are an early bird. Wi-Fi will not be affected. Contact facilities@sanctuary.com with any concerns.',
    priority: 'normal',
    tags: ['maintenance', 'facilities'],
    isPinned: false,
    readBy: ['user-1', 'user-2', 'user-3', 'user-4', 'user-5'],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'ann-4',
    authorId: 'staff-1',
    authorName: 'Sanctuary Team',
    authorRole: 'Community',
    title: 'Sanctuary Perks Program Update',
    content: 'We have added 12 new perks to the Sanctuary Perks Program this month! Highlights include: $100K AWS credits, 50% off Notion for Teams, free 6-month Figma Pro licenses, and discounted legal services through Alvarez Law Group. Check the perks page for the full list and redemption instructions.',
    priority: 'normal',
    tags: ['perks', 'benefits'],
    isPinned: false,
    readBy: ['user-2', 'user-3'],
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'ann-5',
    authorId: 'staff-1',
    authorName: 'Sanctuary Team',
    authorRole: 'Community',
    title: 'URGENT: Fire drill scheduled for Wednesday 11 AM',
    content: 'A mandatory fire drill is scheduled for Wednesday at 11 AM. Please ensure you know the location of your nearest emergency exit. The drill will last approximately 15 minutes. Gather at the designated assembly point in the parking lot. This is mandatory for all residents, staff, and visitors present in the building.',
    priority: 'urgent',
    tags: ['safety', 'mandatory'],
    isPinned: true,
    readBy: ['user-1'],
    createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
  },
]

// Helper function to initialize store with mock data
export function initializeMockData() {
  return {
    residents: mockResidents,
    events: mockEvents,
    checkIns: mockCheckIns,
    visitors: mockVisitors,
    posts: mockPosts,
    celebrations: mockCelebrations,
    mentors: mockMentors,
    discussions: mockDiscussions,
    announcements: mockAnnouncements,
  }
}
