import type {
  KYRProfile,
  CommunityEvent,
  CheckIn,
  BoardPost,
  Celebration,
  Visitor,
} from '@/types'

export const mockResidents: KYRProfile[] = [
  {
    id: 'res-1',
    userId: 'user-1',
    fullName: 'Alex Chen',
    preferredName: 'Alex',
    pronouns: 'they/them',
    role: 'Founder',
    company: 'NeuralPath AI',
    workingOn: 'AI-powered legal document analysis',
    expertise: ['Machine Learning', 'Python', 'Product Strategy'],
    seeking: ['Frontend Engineer', 'Legal Advisor', 'Seed Funding'],
    workStyle: 'early-bird',
    collaborationPreference: 'pair',
    noisePreference: 'ambient',
    meetingPreference: 'morning',
    hometown: 'San Francisco, CA',
    languages: ['English', 'Mandarin'],
    hobbies: ['Rock Climbing', 'Board Games', 'Photography'],
    dietaryRestrictions: ['Vegetarian'],
    favoriteCuisine: ['Japanese', 'Mexican'],
    coffeeOrder: 'Oat milk latte',
    superpower: 'Can debug any code at 2am',
    currentlyReading: 'The Lean Startup',
    walkSong: 'Eye of the Tiger',
    slackHandle: '@alex.chen',
    linkedIn: 'linkedin.com/in/alexchen',
    avatarUrl: undefined,
    bio: 'Building the future of legal tech. Previously at Google.',
    isPublic: true,
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'res-2',
    userId: 'user-2',
    fullName: 'Sarah Johnson',
    preferredName: 'Sarah',
    pronouns: 'she/her',
    role: 'CTO',
    company: 'GreenMetrics',
    workingOn: 'Sustainability tracking platform for enterprises',
    expertise: ['React', 'Node.js', 'AWS', 'Climate Tech'],
    seeking: ['Climate Data Partners', 'Series A Investors'],
    workStyle: 'flexible',
    collaborationPreference: 'team',
    noisePreference: 'any',
    meetingPreference: 'afternoon',
    hometown: 'Austin, TX',
    languages: ['English', 'Spanish'],
    hobbies: ['Hiking', 'Cooking', 'Yoga'],
    dietaryRestrictions: [],
    favoriteCuisine: ['Thai', 'Italian'],
    coffeeOrder: 'Cold brew, black',
    superpower: 'Remembers everyone\'s name',
    currentlyWatching: 'Severance',
    slackHandle: '@sarah.j',
    avatarUrl: undefined,
    bio: 'Making sustainability measurable. 10+ years in enterprise software.',
    isPublic: true,
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-02-15T00:00:00Z',
  },
  {
    id: 'res-3',
    userId: 'user-3',
    fullName: 'Marcus Williams',
    preferredName: 'Marc',
    pronouns: 'he/him',
    role: 'Founder',
    company: 'FinFlow',
    workingOn: 'Automated bookkeeping for freelancers',
    expertise: ['Finance', 'UX Design', 'Flutter'],
    seeking: ['Mobile Developer', 'Accountant Advisors'],
    workStyle: 'night-owl',
    collaborationPreference: 'solo',
    noisePreference: 'silent',
    meetingPreference: 'evening',
    hometown: 'Chicago, IL',
    languages: ['English'],
    hobbies: ['Jazz Piano', 'Chess', 'Running'],
    dietaryRestrictions: ['Gluten-free'],
    favoriteCuisine: ['Korean', 'Indian'],
    coffeeOrder: 'Espresso',
    superpower: 'Can explain any financial concept simply',
    currentlyReading: 'Zero to One',
    slackHandle: '@marc.w',
    linkedIn: 'linkedin.com/in/marcuswilliams',
    avatarUrl: undefined,
    bio: 'Former Goldman Sachs. Democratizing financial tools.',
    isPublic: true,
    createdAt: '2024-01-20T00:00:00Z',
    updatedAt: '2024-02-10T00:00:00Z',
  },
  {
    id: 'res-4',
    userId: 'user-4',
    fullName: 'Priya Sharma',
    preferredName: 'Priya',
    pronouns: 'she/her',
    role: 'Designer',
    company: 'Freelance',
    workingOn: 'Building my design studio',
    expertise: ['Brand Design', 'Figma', 'Motion Design', 'Web3'],
    seeking: ['Startup Clients', 'Design Partners'],
    workStyle: 'flexible',
    collaborationPreference: 'any',
    noisePreference: 'music',
    meetingPreference: 'morning',
    hometown: 'Mumbai, India',
    languages: ['English', 'Hindi', 'Marathi'],
    hobbies: ['Illustration', 'Dance', 'Travel'],
    dietaryRestrictions: ['Vegetarian', 'No eggs'],
    favoriteCuisine: ['Indian', 'Mediterranean'],
    coffeeOrder: 'Chai latte',
    superpower: 'Turns complex ideas into simple visuals',
    currentlyWatching: 'Abstract: The Art of Design',
    slackHandle: '@priya.design',
    personalSite: 'priyasharma.design',
    avatarUrl: undefined,
    bio: 'Award-winning designer. Making startups look good.',
    isPublic: true,
    createdAt: '2024-02-05T00:00:00Z',
    updatedAt: '2024-02-20T00:00:00Z',
  },
  {
    id: 'res-5',
    userId: 'user-5',
    fullName: 'James O\'Connor',
    preferredName: 'JC',
    pronouns: 'he/him',
    role: 'Engineer',
    company: 'DataSync',
    workingOn: 'Real-time data sync infrastructure',
    expertise: ['Rust', 'Distributed Systems', 'PostgreSQL'],
    seeking: ['Co-founder', 'Angel Investment'],
    workStyle: 'early-bird',
    collaborationPreference: 'pair',
    noisePreference: 'ambient',
    meetingPreference: 'any',
    hometown: 'Dublin, Ireland',
    languages: ['English', 'Irish'],
    hobbies: ['Rugby', 'Whiskey Tasting', 'Woodworking'],
    dietaryRestrictions: [],
    favoriteCuisine: ['Irish', 'BBQ'],
    coffeeOrder: 'Americano',
    superpower: 'Optimizes everything, including breakfast routine',
    currentlyReading: 'Designing Data-Intensive Applications',
    slackHandle: '@jc.oconnor',
    avatarUrl: undefined,
    bio: 'Ex-Stripe infrastructure. Building better databases.',
    isPublic: true,
    createdAt: '2024-01-25T00:00:00Z',
    updatedAt: '2024-02-18T00:00:00Z',
  },
]

export const mockEvents: CommunityEvent[] = [
  {
    id: 'evt-1',
    title: 'Founder Lunch & Learn: Fundraising 101',
    description: 'Join us for a casual lunch where we\'ll discuss the basics of fundraising, from pitch decks to term sheets. Bring your questions!',
    category: 'learning',
    date: new Date().toISOString().split('T')[0],
    startTime: '12:00',
    endTime: '13:30',
    isAllDay: false,
    isRecurring: true,
    recurrencePattern: 'Every Thursday',
    location: 'Collab Zone',
    isVirtual: false,
    capacity: 20,
    spotsRemaining: 8,
    hasWaitlist: true,
    hostId: 'mentor-1',
    hostName: 'David Park',
    rsvpCount: 12,
    comments: [],
    tags: ['fundraising', 'lunch', 'learning'],
    isHighlight: true,
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'evt-2',
    title: 'Rooftop Social: Friday Sunset',
    description: 'End the week right! Join fellow founders and the Sanctuary team for drinks and conversation on the rooftop. Bring a friend!',
    category: 'social',
    date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    startTime: '17:00',
    endTime: '20:00',
    isAllDay: false,
    isRecurring: true,
    recurrencePattern: 'Every Friday',
    location: 'Rooftop',
    isVirtual: false,
    capacity: 50,
    spotsRemaining: 35,
    hasWaitlist: false,
    hostId: 'staff-1',
    hostName: 'Sanctuary Team',
    rsvpCount: 15,
    comments: [],
    tags: ['social', 'networking', 'drinks'],
    isHighlight: true,
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'evt-3',
    title: 'Morning Meditation',
    description: 'Start your day with 20 minutes of guided meditation. All levels welcome. Mats provided.',
    category: 'wellness',
    date: new Date().toISOString().split('T')[0],
    startTime: '08:00',
    endTime: '08:30',
    isAllDay: false,
    isRecurring: true,
    recurrencePattern: 'Mon, Wed, Fri',
    location: 'Quiet Zone',
    isVirtual: false,
    capacity: 10,
    spotsRemaining: 6,
    hasWaitlist: false,
    hostId: 'res-4',
    hostName: 'Priya Sharma',
    rsvpCount: 4,
    comments: [],
    tags: ['wellness', 'meditation', 'morning'],
    isHighlight: false,
    createdAt: '2024-02-10T00:00:00Z',
  },
  {
    id: 'evt-4',
    title: 'Demo Day: February Cohort',
    description: 'Watch 5 startups from our February cohort present their progress. Investors and mentors welcome.',
    category: 'pitch',
    date: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
    startTime: '14:00',
    endTime: '17:00',
    isAllDay: false,
    isRecurring: false,
    location: 'Main Event Space',
    isVirtual: true,
    virtualLink: 'https://zoom.us/j/example',
    capacity: 100,
    spotsRemaining: 45,
    hasWaitlist: true,
    hostId: 'staff-1',
    hostName: 'Sanctuary Team',
    rsvpCount: 55,
    comments: [],
    tags: ['demo', 'pitch', 'investors'],
    isHighlight: true,
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'evt-5',
    title: 'Design Systems Workshop',
    description: 'Learn how to build scalable design systems for your startup. Priya will share her framework and tools.',
    category: 'workshop',
    date: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
    startTime: '15:00',
    endTime: '17:00',
    isAllDay: false,
    isRecurring: false,
    location: 'Meeting Room A',
    isVirtual: false,
    capacity: 15,
    spotsRemaining: 3,
    hasWaitlist: true,
    hostId: 'res-4',
    hostName: 'Priya Sharma',
    rsvpCount: 12,
    comments: [],
    tags: ['design', 'workshop', 'figma'],
    isHighlight: false,
    createdAt: '2024-02-15T00:00:00Z',
  },
]

export const mockCheckIns: CheckIn[] = [
  {
    id: 'ci-1',
    userId: 'user-2',
    userName: 'Sarah Johnson',
    userRole: 'CTO',
    userCompany: 'GreenMetrics',
    checkInTime: new Date(Date.now() - 3600000 * 3).toISOString(),
    location: 'main-floor',
    status: 'Heads down on funding deck',
    isVisitor: false,
  },
  {
    id: 'ci-2',
    userId: 'user-3',
    userName: 'Marcus Williams',
    userRole: 'Founder',
    userCompany: 'FinFlow',
    checkInTime: new Date(Date.now() - 3600000 * 2).toISOString(),
    location: 'quiet-zone',
    status: 'Deep work mode - shipping v2',
    isVisitor: false,
  },
  {
    id: 'ci-3',
    userId: 'user-4',
    userName: 'Priya Sharma',
    userRole: 'Designer',
    checkInTime: new Date(Date.now() - 3600000).toISOString(),
    location: 'collab-zone',
    status: 'Open to chat about design!',
    isVisitor: false,
  },
  {
    id: 'ci-4',
    userId: 'user-5',
    userName: 'James O\'Connor',
    userRole: 'Engineer',
    userCompany: 'DataSync',
    checkInTime: new Date(Date.now() - 1800000).toISOString(),
    location: 'cafe',
    status: 'Coffee + code review',
    isVisitor: false,
  },
]

export const mockVisitors: Visitor[] = [
  {
    id: 'vis-1',
    name: 'Michael Torres',
    company: 'Sequoia Capital',
    purpose: 'Meeting with GreenMetrics',
    hostId: 'user-2',
    hostName: 'Sarah Johnson',
    checkInTime: new Date(Date.now() - 1800000).toISOString(),
    badgeNumber: 'V-042',
  },
  {
    id: 'vis-2',
    name: 'Emily Zhang',
    company: 'TechCrunch',
    purpose: 'Interview with founders',
    hostId: 'staff-1',
    hostName: 'Sanctuary Team',
    checkInTime: new Date(Date.now() - 3600000).toISOString(),
    badgeNumber: 'V-043',
  },
]

export const mockPosts: BoardPost[] = [
  {
    id: 'post-1',
    authorId: 'user-4',
    authorName: 'Priya Sharma',
    title: '🎨 Offering free logo feedback this week!',
    content: 'Working on a blog post about startup branding. Happy to give quick feedback on anyone\'s logo or brand identity. DM me on Slack!',
    category: 'offer',
    reactions: [
      { emoji: '🙏', count: 5, userIds: ['user-1', 'user-2', 'user-3', 'user-5', 'user-6'] },
      { emoji: '❤️', count: 3, userIds: ['user-1', 'user-2', 'user-7'] },
    ],
    commentCount: 4,
    isPinned: false,
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'post-2',
    authorId: 'staff-1',
    authorName: 'Sanctuary Team',
    title: '📢 Building maintenance: Sunday 6am-9am',
    content: 'Quick heads up - there will be scheduled maintenance this Sunday morning. Building will be accessible but elevators may be offline. Plan ahead if you\'re an early bird!',
    category: 'announcement',
    reactions: [
      { emoji: '👍', count: 8, userIds: ['user-1', 'user-2', 'user-3', 'user-4', 'user-5', 'user-6', 'user-7', 'user-8'] },
    ],
    commentCount: 2,
    isPinned: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'post-3',
    authorId: 'user-3',
    authorName: 'Marcus Williams',
    title: 'Looking for React Native dev recommendations',
    content: 'We\'re expanding the FinFlow mobile app and looking for contractor recommendations. Anyone worked with great RN devs recently?',
    category: 'ask',
    reactions: [
      { emoji: '🤔', count: 2, userIds: ['user-1', 'user-5'] },
    ],
    commentCount: 6,
    isPinned: false,
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'post-4',
    authorId: 'user-5',
    authorName: 'James O\'Connor',
    title: '🎉 Shoutout to Alex for the debugging help!',
    content: 'Spent 3 hours on a race condition yesterday. Alex walked by, looked at my screen for 30 seconds, and found it. True superpower!',
    category: 'shoutout',
    reactions: [
      { emoji: '🎉', count: 12, userIds: ['user-2', 'user-3', 'user-4', 'user-6', 'user-7', 'user-8', 'user-9', 'user-10', 'user-11', 'user-12', 'user-13', 'user-14'] },
      { emoji: '🧙', count: 4, userIds: ['user-2', 'user-3', 'user-4', 'user-5'] },
    ],
    commentCount: 3,
    isPinned: false,
    createdAt: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
]

export const mockCelebrations: Celebration[] = [
  {
    id: 'cel-1',
    userId: 'user-2',
    userName: 'Sarah Johnson',
    type: 'funding',
    title: 'GreenMetrics raised $2M seed!',
    description: 'Led by Sequoia Capital',
    date: new Date().toISOString().split('T')[0],
  },
  {
    id: 'cel-2',
    userId: 'user-5',
    userName: 'James O\'Connor',
    type: 'birthday',
    title: 'Happy Birthday JC!',
    date: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
  },
  {
    id: 'cel-3',
    userId: 'user-1',
    userName: 'Alex Chen',
    type: 'work-anniversary',
    title: '1 year at Sanctuary!',
    date: new Date(Date.now() + 4 * 86400000).toISOString().split('T')[0],
  },
]

// Helper function to initialize store with mock data
export function initializeMockData() {
  return {
    residents: mockResidents,
    events: mockEvents,
    checkIns: mockCheckIns,
    visitors: mockVisitors,
    posts: mockPosts,
    celebrations: mockCelebrations,
  }
}
