import type { Founder } from '@/types'

export const founders: Founder[] = [
  // TechFlow AI founders
  {
    id: 'founder-1',
    startupId: 'startup-1',
    name: 'Sarah Chen',
    email: 'sarah@techflow.ai',
    role: 'CEO',
    isLead: true,
    photoUrl: null,
    bio: 'Former ML engineer at Google. 10+ years in enterprise AI. Stanford CS PhD.',
    linkedin: 'https://linkedin.com/in/sarahchen',
    twitter: 'sarahchen_ai',
    personalSite: 'https://sarahchen.dev',
    previousCompanies: ['Google', 'DeepMind'],
    previousExits: false,
    yearsExperience: 12,
    education: 'PhD Computer Science, Stanford',
    skillTechnical: 5,
    skillProduct: 4,
    skillSales: 3,
    skillDesign: 2,
    skillLeadership: 4,
    whyThisProblem: 'Spent years watching enterprises struggle with ML ops. The tooling is broken.',
    longTermAmbition: 'Build the operating system for enterprise AI.',
    createdAt: '2026-01-20T00:00:00Z',
    updatedAt: '2026-01-20T00:00:00Z',
  },
  {
    id: 'founder-2',
    startupId: 'startup-1',
    name: 'Marcus Rivera',
    email: 'marcus@techflow.ai',
    role: 'CTO',
    isLead: false,
    photoUrl: null,
    bio: 'Ex-Stripe infrastructure lead. Built systems handling millions of requests.',
    linkedin: 'https://linkedin.com/in/marcusrivera',
    twitter: 'marcusdev',
    personalSite: null,
    previousCompanies: ['Stripe', 'Cloudflare'],
    previousExits: false,
    yearsExperience: 8,
    education: 'MS Computer Science, MIT',
    skillTechnical: 5,
    skillProduct: 3,
    skillSales: 2,
    skillDesign: 2,
    skillLeadership: 3,
    whyThisProblem: 'Infrastructure is my passion. ML infrastructure is the next frontier.',
    longTermAmbition: null,
    createdAt: '2026-01-20T00:00:00Z',
    updatedAt: '2026-01-20T00:00:00Z',
  },

  // GreenCommute founders
  {
    id: 'founder-3',
    startupId: 'startup-2',
    name: 'Emma Johansson',
    email: 'emma@greencommute.co',
    role: 'CEO',
    isLead: true,
    photoUrl: null,
    bio: 'Climate tech advocate. Former sustainability consultant at McKinsey.',
    linkedin: 'https://linkedin.com/in/emmajohansson',
    twitter: 'emma_climate',
    personalSite: null,
    previousCompanies: ['McKinsey', 'Tesla'],
    previousExits: false,
    yearsExperience: 7,
    education: 'MBA, INSEAD',
    skillTechnical: 2,
    skillProduct: 4,
    skillSales: 5,
    skillDesign: 3,
    skillLeadership: 4,
    whyThisProblem: 'Corporate emissions are solvable. Someone needs to build the tools.',
    longTermAmbition: 'Make corporate sustainability the default, not the exception.',
    createdAt: '2026-01-22T00:00:00Z',
    updatedAt: '2026-01-22T00:00:00Z',
  },

  // HealthBridge founders
  {
    id: 'founder-4',
    startupId: 'startup-3',
    name: 'Dr. Aisha Patel',
    email: 'aisha@healthbridge.io',
    role: 'CEO',
    isLead: true,
    photoUrl: null,
    bio: 'Physician turned entrepreneur. Frustrated by broken healthcare communication.',
    linkedin: 'https://linkedin.com/in/draishapatel',
    twitter: null,
    personalSite: null,
    previousCompanies: ['Johns Hopkins Hospital'],
    previousExits: false,
    yearsExperience: 15,
    education: 'MD, Johns Hopkins; MBA, Wharton',
    skillTechnical: 2,
    skillProduct: 5,
    skillSales: 3,
    skillDesign: 2,
    skillLeadership: 5,
    whyThisProblem: 'I\'ve seen patients suffer from poor communication. It\'s fixable.',
    longTermAmbition: 'Zero preventable deaths from miscommunication in healthcare.',
    createdAt: '2026-01-23T00:00:00Z',
    updatedAt: '2026-01-23T00:00:00Z',
  },
  {
    id: 'founder-5',
    startupId: 'startup-3',
    name: 'James Wong',
    email: 'james@healthbridge.io',
    role: 'CTO',
    isLead: false,
    photoUrl: null,
    bio: 'Healthcare IT specialist. Built EHR integrations at Epic.',
    linkedin: 'https://linkedin.com/in/jameswong',
    twitter: null,
    personalSite: null,
    previousCompanies: ['Epic Systems', 'Cerner'],
    previousExits: false,
    yearsExperience: 10,
    education: 'BS Computer Science, UC Berkeley',
    skillTechnical: 5,
    skillProduct: 3,
    skillSales: 1,
    skillDesign: 2,
    skillLeadership: 3,
    whyThisProblem: 'Healthcare data is siloed. I know how to connect it.',
    longTermAmbition: null,
    createdAt: '2026-01-23T00:00:00Z',
    updatedAt: '2026-01-23T00:00:00Z',
  },

  // FinLit founders
  {
    id: 'founder-6',
    startupId: 'startup-4',
    name: 'David Okonkwo',
    email: 'david@finlit.app',
    role: 'CEO',
    isLead: true,
    photoUrl: null,
    bio: 'Former teacher, fintech product manager. Passionate about financial inclusion.',
    linkedin: 'https://linkedin.com/in/davidokonkwo',
    twitter: 'david_finlit',
    personalSite: null,
    previousCompanies: ['Chime', 'Teach for America'],
    previousExits: false,
    yearsExperience: 6,
    education: 'BA Economics, Howard University',
    skillTechnical: 3,
    skillProduct: 5,
    skillSales: 4,
    skillDesign: 3,
    skillLeadership: 4,
    whyThisProblem: 'Financial literacy shouldn\'t be a privilege. It\'s a right.',
    longTermAmbition: 'Make every young person financially confident.',
    createdAt: '2026-01-24T00:00:00Z',
    updatedAt: '2026-01-24T00:00:00Z',
  },

  // BuildRight founders
  {
    id: 'founder-7',
    startupId: 'startup-5',
    name: 'Carlos Mendez',
    email: 'carlos@buildright.co',
    role: 'CEO',
    isLead: true,
    photoUrl: null,
    bio: 'Third-generation contractor. Knows construction inside out.',
    linkedin: 'https://linkedin.com/in/carlosmendez',
    twitter: null,
    personalSite: null,
    previousCompanies: ['Mendez Construction', 'Skanska'],
    previousExits: true,
    yearsExperience: 20,
    education: 'Civil Engineering, UT Austin',
    skillTechnical: 3,
    skillProduct: 3,
    skillSales: 5,
    skillDesign: 2,
    skillLeadership: 5,
    whyThisProblem: 'Construction is 200 years behind. Time to fix it.',
    longTermAmbition: 'Digitize the entire construction value chain.',
    createdAt: '2026-01-25T00:00:00Z',
    updatedAt: '2026-01-25T00:00:00Z',
  },
  {
    id: 'founder-8',
    startupId: 'startup-5',
    name: 'Nina Kowalski',
    email: 'nina@buildright.co',
    role: 'CTO',
    isLead: false,
    photoUrl: null,
    bio: 'Software architect from Autodesk. BIM and construction tech expert.',
    linkedin: 'https://linkedin.com/in/ninakowalski',
    twitter: 'nina_builds',
    personalSite: null,
    previousCompanies: ['Autodesk', 'Procore'],
    previousExits: false,
    yearsExperience: 9,
    education: 'MS Software Engineering, Carnegie Mellon',
    skillTechnical: 5,
    skillProduct: 4,
    skillSales: 2,
    skillDesign: 3,
    skillLeadership: 3,
    whyThisProblem: 'Software can solve construction chaos. I\'ve seen it work.',
    longTermAmbition: null,
    createdAt: '2026-01-25T00:00:00Z',
    updatedAt: '2026-01-25T00:00:00Z',
  },
]

export function getFoundersByStartupId(startupId: string): Founder[] {
  return founders.filter((f) => f.startupId === startupId)
}

export function getFounderById(id: string): Founder | undefined {
  return founders.find((f) => f.id === id)
}

export function getLeadFounder(startupId: string): Founder | undefined {
  return founders.find((f) => f.startupId === startupId && f.isLead)
}
