"use client";

import Link from "next/link";
import {
  ArrowRight,
  BarChart3,
  Brain,
  Eye,
  Handshake,
  ShieldCheck,
  TrendingUp,
} from "lucide-react";
import { motion } from "framer-motion";
import { Hero } from "@/components/Hero";
import { SectionHeader } from "@/components/SectionHeader";
import { FeatureCard } from "@/components/FeatureCard";

const investorBenefits = [
  {
    icon: <BarChart3 size={24} />,
    title: "AI-Powered DD Reports",
    description:
      "Comprehensive due diligence reports generated by our AI pipeline: claim extraction, verification, and risk analysis delivered in hours, not weeks.",
  },
  {
    icon: <Eye size={24} />,
    title: "Portfolio Dashboard",
    description:
      "Real-time visibility into portfolio company metrics, milestones, and investment performance through a unified partner dashboard.",
  },
  {
    icon: <Brain size={24} />,
    title: "Smart Deal Flow",
    description:
      "AI-curated deal flow based on your investment thesis, stage preference, and sector expertise. Quality over quantity.",
  },
];

const mentorBenefits = [
  {
    icon: <Handshake size={24} />,
    title: "AI-Matched Founders",
    description:
      "Get matched with founders where your expertise makes the biggest impact. Our AI analyses compatibility across 50+ dimensions.",
  },
  {
    icon: <TrendingUp size={24} />,
    title: "Track Your Impact",
    description:
      "See the measurable impact of your mentorship through founder progress dashboards, milestone tracking, and outcome metrics.",
  },
  {
    icon: <ShieldCheck size={24} />,
    title: "Flexible Commitment",
    description:
      "Mentor on your schedule. Our platform makes it easy to provide async feedback, schedule sessions, and collaborate with founders.",
  },
];

const partnerTypes = [
  {
    title: "Angel Investors",
    description: "Get early access to curated startups with AI-verified DD. Co-invest alongside our fund with standard terms.",
    cta: "Join as Investor",
  },
  {
    title: "VC Partners",
    description: "Access our pipeline for Series A+ opportunities. Receive warm introductions to the strongest graduating founders.",
    cta: "Partner with Us",
  },
  {
    title: "Mentors & Advisors",
    description: "Share your expertise with the next generation. Flexible time commitment, AI-matched for maximum impact.",
    cta: "Become a Mentor",
  },
  {
    title: "Corporate Partners",
    description: "Sponsor credits, offer pilot programmes, or integrate with our startups. First-mover advantage on emerging tech.",
    cta: "Explore Partnership",
  },
];

export default function PartnersPage() {
  return (
    <>
      <Hero
        badge="Partner Network"
        title="Invest, Mentor, and"
        titleAccent="Shape the Future"
        subtitle="Join our network of investors, mentors, and corporate partners. Get AI-powered tools to discover, evaluate, and support the most promising startups."
        primaryCta={{ label: "Get Involved", href: "/contact" }}
        secondaryCta={{ label: "View Programme", href: "/programme" }}
      />

      {/* For Investors */}
      <section className="py-24">
        <div className="mx-auto max-w-6xl px-6">
          <SectionHeader
            label="For Investors"
            title="Smarter Investment Decisions"
            description="AI-powered due diligence, real-time portfolio tracking, and curated deal flow designed for modern investors."
          />

          <div className="grid gap-6 md:grid-cols-3">
            {investorBenefits.map((benefit, i) => (
              <FeatureCard
                key={benefit.title}
                icon={benefit.icon}
                title={benefit.title}
                description={benefit.description}
                index={i}
              />
            ))}
          </div>
        </div>
      </section>

      {/* For Mentors */}
      <section className="border-y border-border bg-secondary/30 py-24">
        <div className="mx-auto max-w-6xl px-6">
          <SectionHeader
            label="For Mentors"
            title="Mentorship That Scales"
            description="We match your expertise with the founders who need it most. Track your impact in real time."
          />

          <div className="grid gap-6 md:grid-cols-3">
            {mentorBenefits.map((benefit, i) => (
              <FeatureCard
                key={benefit.title}
                icon={benefit.icon}
                title={benefit.title}
                description={benefit.description}
                index={i}
              />
            ))}
          </div>
        </div>
      </section>

      {/* How to Get Involved */}
      <section className="py-24">
        <div className="mx-auto max-w-6xl px-6">
          <SectionHeader
            label="Get Involved"
            title="Ways to Partner"
          />

          <div className="grid gap-6 sm:grid-cols-2">
            {partnerTypes.map((type, i) => (
              <motion.div
                key={type.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.5, delay: i * 0.1 }}
                className="flex flex-col rounded-2xl border border-border bg-card p-8"
              >
                <h3 className="mb-3 text-lg font-semibold">{type.title}</h3>
                <p className="mb-6 flex-1 text-sm leading-relaxed text-muted-foreground">
                  {type.description}
                </p>
                <Link
                  href="/contact"
                  className="group inline-flex items-center gap-2 text-sm font-medium text-primary transition-colors hover:text-primary/80"
                >
                  {type.cta}
                  <ArrowRight size={14} className="transition-transform group-hover:translate-x-0.5" />
                </Link>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="border-t border-border bg-primary py-20">
        <div className="mx-auto max-w-3xl px-6 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
          >
            <h2 className="text-3xl font-bold text-primary-foreground sm:text-4xl">
              Join the Network
            </h2>
            <p className="mt-4 text-lg text-primary-foreground/70">
              Whether you are an investor, mentor, or corporate partner, we would
              love to hear from you.
            </p>
            <Link
              href="/contact"
              className="group mt-8 inline-flex items-center gap-2 rounded-xl bg-background px-6 py-3 text-sm font-medium text-foreground shadow-lg transition-all hover:shadow-xl"
            >
              Contact Us
              <ArrowRight
                size={16}
                className="transition-transform group-hover:translate-x-0.5"
              />
            </Link>
          </motion.div>
        </div>
      </section>
    </>
  );
}
